### ISSUE TITLE
memory errorが起きてしまう

### ISSUE THREAD

**Issue by 63492harada** [molecule-generator-collection/ChemTSv2#23]
chemTSv2を起動した瞬間にGPUのmemoryの大半が使われてしまい、その後GPUを報酬関数の中で利用しようとするとmemory errorが起きてしまいます。
使用する前のGPUは1MiB / 24576MiBですが、ChemTS使用後は23657MiB / 24576MiBが使用されています。
要因、改善方法等をご教授いただきたいです。

**Comment by sishida21** [comment]
Issueを作る際にBug reportというテンプレートが表示されると思いますので、そちらの様式を埋めて質問しなおしてください。記載の内容ではこちらで調べられません。
