### ISSUE TITLE
Good software package, excuse me, how to obtain the rdkit: 2021.03.5

### ISSUE THREAD

**Issue by 2455574606** [molecule-generator-collection/ChemTSv2#26]

**Comment by sishida21** [comment]
@2455574606,
Please try the following command:
```bash
pip install rdkit-pypi==2021.3.5
```

Hope this helps.

**Comment by 2455574606** [comment]
![image](https://user-images.githubusercontent.com/129136983/228470245-b810f9b0-fa89-4306-9201-dffc4eaa6550.png)

**Comment by 2455574606** [comment]
Excuse me again

**Comment by sishida21** [comment]
First of all, I am sorry to say that ChemTSv2 does not support Windows OS (i.e., we do not confirm that it works correctly). From the error message, it looks like you need to specify version 2021.3.5.1.

**Comment by 2455574606** [comment]
Thank you for your answer.
