### ISSUE TITLE
ModuleNotFoundError for TensorFlow in Docker container

### ISSUE THREAD

**Issue by tomoish** [molecule-generator-collection/ChemTSv2#35]
**Describe the bug**
When attempting to run a Docker container, I encounter a `ModuleNotFoundError` stating that the TensorFlow module is missing, despite being listed as a dependency in `pyproject.toml`.

**To Reproduce**
1. `docker build -t chemtsv2:1.0.0 .`
2. 
      ```bash
      docker run -u $(id -u):$(id -g) \
       --rm \
      --mount type=bind,source=./,target=/app/ \
      chemtsv2:1.0.0 \
      chemtsv2 -c config/setting.yaml
      ```

**Expected behavior**
The application should start without any ImportError, with all dependencies, including TensorFlow, correctly installed and available.

**Screenshots**
![ChemTSv2_error](https://github.com/molecule-generator-collection/ChemTSv2/assets/103555868/0fea8b51-6c17-4b72-9173-7d3e5a4f5916)

**Environments**
 - OS: MacOS
 - Version: Ventura 13.4
 - Docker version: 24.0.6, build ed223bc

**Comment by sishida21** [comment]
I missed this Pull Request https://github.com/molecule-generator-collection/ChemTSv2/pull/36. Thank you for sharing the workaround in your environment. I will check it.

**Comment by sishida21** [comment]
I finished checking it.
To conclude, the `--no-deps` option is necessary. Without it, there's a risk of overriding the package versions fixed in `poetry.lock`, which could lead to bugs in the environment setup in the future.

**Comment by tomoish** [comment]
@sishida21 
Thank you for taking the time to investigate this issue. After reviewing your findings, I realize that the error was on my part due to using MacOS with ARM architecture, as you pointed out. I appreciate your help in identifying this.
Thanks again for your assistance.

**Comment by sishida21** [comment]
@tomoish Thank you for attempting to use ChemTSv2. We plan to continue developing ChemTSv2 to ensure it can be used on ARM architecture in the future.
