### ISSUE TITLE
QSAR predictive model does not work

### ISSUE THREAD

**Issue by Fishundergraduate** [molecule-generator-collection/ChemTSv2#43]
**Describe the bug**
when `'data/model/lgb_models.pickle'` loads in `dscore_reward.py`, it cannot run in  L58.

**To Reproduce**
1. create an environment on conda
2. run `pip install --upgrade chemtsv2`
3. run `pip install lightgbm`
4. run `chemtsv2 -c config/setting_dscore.yaml`

**Expected behavior**
generated molecule.
Moreover, `return lgb_models["EGFR"].predict(fp)[0]` evaluates the reward score.

**Screenshots**
If applicable, add screenshots to help explain your problem.- No.

**Environments (please complete the following information):**
 - OS: Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
 - CUDA Toolkit version : 11.8
 - NVIDIA driver version: 535.86.10

**Additional context**
When  `lgb_models["EGFR"]` changes into `lgb_egfr`, which is loaded from `'data/model/lgb_egfr.pickle'`, it was succeeded. In that case, the following lines occurred errors like the EGFR.
If this happens in my specific circumstance, I'm sorry to take your time.

**Comment by sishida21** [comment]
@Fishundergraduate Thank you for sharing the issue you encountered. I think this is the version problem of LightGBM. Could you try installing chemtsv2 and lightgbm packages in a new virtual environment again using the following command.

```bash
pip install chemtsv2 lightgbm==3.2.1
```

**Comment by Fishundergraduate** [comment]
Thank you for your quick reply! It gets well with downgrading the lightgbm version.
I solved the issue.

**Comment by sishida21** [comment]
I've updated the README to work around this issue. Thanks again for reporting the issue.
