### ISSUE TITLE
lightgbmのインストールに関する問題

### ISSUE THREAD

**Issue by Takuto-Koyama** [molecule-generator-collection/ChemTSv2#46]
**Issue: lightgbmのインストールに関する問題**
概要
ChemTSv2の環境構築時に、lightgbmのインストールが自動で行われず、ユーザーが手動でインストールする必要がありました。また、最新バージョンのlightgbmをインストールするとエラーが発生したため、`lightgbm == 3.3.5` である必要がありました。

**Comment by sishida21** [comment]
rewardのみで使うパッケージはchemtsv2自体の依存関係には含めていません。各rewardの使い方は[reward/README](https://github.com/molecule-generator-collection/ChemTSv2/tree/master/reward) に記載があり、追加で必要なパッケージがある場合はそれについても記載してます。また全てのrewardに説明があるわけではないのでそれはご了承ください。

たとえばdscore_reward.pyを利用している場合は以下に記載の通り
3.2.1を別途インストールする必要があります。
`pip install chemtsv2 lightgbm==3.2.1` 
https://github.com/molecule-generator-collection/ChemTSv2/tree/master/reward#dscore_rewardpy

**Comment by Takuto-Koyama** [comment]
ご教示いただき、ありがとうございます。
